### ISSUE TITLE
Does not work?

### ISSUE THREAD

**Issue by thoni56** [cividesk/com.cividesk.l10n.update#16]
Our `civicrm/l10n` directory has not been updated since I created it. How do I know this extension actually is doing anything? Is there a log somewhere?

I have visited the localization and extension pages multiple times. But no downloads...

**Comment by thoni56** [comment]
I really like to get this extension working in our installation. @mattwire are there any logs or other things I can look at to see why it does not update the translation files?

Are there any assumptions about directories or similar things that might not apply to our installation?

**Comment by mattwire** [comment]
@thoni56 Please try https://lab.civicrm.org/extensions/uplang instead

**Comment by thoni56** [comment]
Thanks. Perhaps this repo should be archived with a pointer there then?
