### ISSUE TITLE
Archive/deprecate this extension?

### ISSUE THREAD

**Issue by thoni56** [cividesk/com.cividesk.l10n.update#17]
As this extension seems to have been superseeded by https://civicrm.org/extensions/update-language-files maybe it should be archived. And also references to it in the documentation updated to point to `uplang` instead.

**Comment by nganivet** [comment]
@thoni56 Agreed. Can you create pull request with the necessary changes? I will then review and merge. Thanks.

**Comment by thoni56** [comment]
I've pushed an extra commit to #14 to update the README about deprecation. The other commits are kind of irrelevant, but I reused that PR for simplicity.

**Comment by nganivet** [comment]
Merged and closed, thanks.
