### ISSUE TITLE
HTTP 302 response written to localization files instead of actual translations

### ISSUE THREAD

**Issue by herbdool** [cividesk/com.cividesk.l10n.update#6]
When using the extension and refreshing the extensions page it displays a success message that the files have been downloaded. However, the content of the file such as `cat l10n/fr_CA/civicrm.mo` ends up looking like:

```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

There's also this message on the screen:

> WARNING: The downloader may be unable to download files which require HTTP redirection. This may be a configuration issue with PHP's open_basedir or safe_mode.

**Comment by mattwire** [comment]
Fixed via #9
