### ISSUE TITLE
Move to https://lab.civicrm.org/extensions

### ISSUE THREAD

**Issue by mattwire** [cividesk/com.cividesk.l10n.update#8]
@nganivet Can we move this extension to https://lab.civicrm.org/extensions so it is easier to find / update? @mlutfy @aydun @mikeymjco

**Comment by MikeyMJCO** [comment]
I’m keen on this and happy to step up/maintain!

Get Outlook for iOS<https://aka.ms/o0ukef>

MICHAEL O'TOOLE
Managing Director
 T 029 2009 7097
 M 07769 901541
 E mikey@mjco.uk
WWW.MJCO.UK
54 Florentia Street
Cardiff, CF24 4PF
This email was sent whilst on-the-go! Please excuse any unintentional errors or brevity!
 We don't expect you to read a page of terms and conditions all we ask is that you let us know if we sent this to the wrong person and we'd like you to know that nothing in this email is intended to form a binding legal contract. 
 
 MJCO LTD is a company registered in Wales. Registered Number: 08483853. ​Registered Office: 54 Florentia Street, Cardiff CF24 4PF.
 
 
________________________________

**Comment by nganivet** [comment]
Do you have a plan/policy related to this move? Are all extensions moving there? How do we inform people that extensions have moved (I have myself being VERY confused about where to access existing extensions). How has this been communicated to the Community at large?

**Comment by mlutfy** [comment]
> "Do you have a plan/policy related to this move?"

We have been informally encouraging folks to use lab.c.o to store git repos. It's not mandatory, although at some point it might be for release management (i.e. similar to WordPress or Drupal, you can manage elsewhere, but to produce an official release, would require that the code is in lab.c.o).

> "Are all extensions moving there?"

Many have. We're not twisting any arms. For now.

The aim is to make "work-in-progress" extensions more easy to discover. It also makes it easier to have a vendor-neutral space for folks to collaborate.

> "How do we inform people that extensions have moved (I have myself being VERY confused about where to access existing extensions). How has this been communicated to the Community at large?"

If your extension is on civicrm.org/extensions, then you can update the Git Repo there.

If it's not there, then people don't have a way to discover your extension anyway. If you need to communicate a change, the best option is to add the extension to the official listing.

Here are some references:

* https://lab.civicrm.org/extensions/extensions-directory/-/wikis/import-from-github
* https://lab.civicrm.org/extensions/extensions-directory/-/wikis/extension-maintainer-transfer-process

**Comment by nganivet** [comment]
@mattwire I don't see how it makes it easier to find/update as this extension is listed in the extensions directory.
@mlutfy the migration process should probably include editing the README.md in the original repo to point to the new one - that would certainly remove a lot of the confusion out there.
@MikeyMJCO thanks for your offer to maintain, please submit PRs on this github repo for now as I do not currently see value in doing this migration.

**Comment by mlutfy** [comment]
> "the migration process should probably include editing the README.md in the original repo to point to the new one - that would certainly remove a lot of the confusion out there."

It's in there already: https://lab.civicrm.org/extensions/extensions-directory/-/wikis/import-from-github#after-the-migration-to-gitlab :)

**Comment by nganivet** [comment]
Should be added here as well: https://lab.civicrm.org/extensions/extensions-directory/-/wikis/extension-maintainer-transfer-process
